algo = input('Digite algo: ')
print('O tipo primitivo desse valor é:', type(algo))
print('Só tem espaço?', algo.isspace())
print('É um número?', algo.isnumeric())
print('É alfabetico?', algo.isalpha())
print('Alfanumerico', algo.isalnum())
print('Esta em maiusculo?', algo.isupper())
print('Esta em minisculo?', algo.islower())
print('Esta capitalizada?', algo.istitle())  
